"""
This family file was auto-generated by generate_family_file.py script.

Configuration parameters:
  url = https://community.fandom.com/zh
  name = w

Please do not commit this to the Git repository!
"""

from pywikibot import family


class Family(family.Family):  # noqa: D101

    name = "w"
    langs = {
        "zh": "community.fandom.com",
        "ar": "community.fandom.com",
        "ba": "community.fandom.com",
        "bg": "community.fandom.com",
        "ca": "comunitat.fandom.com",
        "cs": "community.fandom.com",
        "de": "community.fandom.com",
        "el": "community.fandom.com",
        "en": "community.fandom.com",
        "es": "comunidad.fandom.com",
        "et": "community.fandom.com",
        "fa": "community.fandom.com",
        "fi": "yhteiso.fandom.com",
        "fr": "communaute.fandom.com",
        "hi": "samuday.fandom.com",
        "hu": "community.fandom.com",
        "id": "community.fandom.com",
        "it": "community.fandom.com",
        "ja": "community.fandom.com",
        "ko": "community.fandom.com",
        "li": "community.fandom.com",
        "lv": "community.fandom.com",
        "nb": "community.fandom.com",
        "nl": "community.fandom.com",
        "no": "community.fandom.com",
        "pl": "spolecznosc.fandom.com",
        "pt": "comunidade.fandom.com",
        "pt-br": "comunidade.fandom.com",
        "ro": "community.fandom.com",
        "ru": "community.fandom.com",
        "tr": "community.fandom.com",
        "uk": "spilnota.fandom.com",
        "vi": "community.fandom.com",
    }

    def scriptpath(self, code):
        return {
            "zh": "/zh",
            "ar": "/ar",
            "ba": "/ba",
            "bg": "/bg",
            "ca": "",
            "cs": "/cs",
            "de": "/de",
            "el": "/el",
            "en": "",
            "es": "",
            "et": "/et",
            "fa": "/fa",
            "fi": "",
            "fr": "/fr",
            "hi": "",
            "hu": "/hu",
            "id": "/id",
            "it": "/it",
            "ja": "/ja",
            "ko": "/ko",
            "li": "/li",
            "lv": "/lv",
            "nb": "/no",
            "nl": "/nl",
            "no": "/no",
            "pl": "",
            "pt": "",
            "pt-br": "",
            "ro": "/ro",
            "ru": "/ru",
            "tr": "/tr",
            "uk": "",
            "vi": "/vi",
        }[code]

    def protocol(self, code):
        return {
            "zh": "https",
            "ar": "https",
            "ba": "https",
            "bg": "https",
            "ca": "https",
            "cs": "https",
            "de": "https",
            "el": "https",
            "en": "https",
            "es": "https",
            "et": "https",
            "fa": "https",
            "fi": "https",
            "fr": "https",
            "hi": "https",
            "hu": "https",
            "id": "https",
            "it": "https",
            "ja": "https",
            "ko": "https",
            "li": "https",
            "lv": "https",
            "nb": "https",
            "nl": "https",
            "no": "https",
            "pl": "https",
            "pt": "https",
            "pt-br": "https",
            "ro": "https",
            "ru": "https",
            "tr": "https",
            "uk": "https",
            "vi": "https",
        }[code]
