from pywikibot import family


class Family(family.Family):  # noqa: D101
    """Fandom community family."""

    name = "w"
    langs = {
        "en": "community.fandom.com",
        "af": "community.fandom.com",
        "ar": "community.fandom.com",
        "be": "community.fandom.com",
        "bg": "community.fandom.com",
        "ca": "comunitat.fandom.com",
        "de": "community.fandom.com",
        "el": "community.fandom.com",
        "es": "comunidad.fandom.com",
        "eshelp": "comunidad.fandom.com",
        "et": "community.fandom.com",
        "fa": "community.fandom.com",
        "fi": "yhteiso.fandom.com",
        "fihelp": "yhteiso.fandom.com",
        "fr": "communaute.fandom.com",
        "frhelp": "communaute.fandom.com",
        "gl": "comunidad.fandom.com",
        "hi": "samuday.fandom.com",
        "hu": "community.fandom.com",
        "id": "community.fandom.com",
        "it": "community.fandom.com",
        "ithelp": "community.fandom.com",
        "ja": "community.fandom.com",
        "jahelp": "community.fandom.com",
        "ko": "community.fandom.com",
        "kohelp": "community.fandom.com",
        "li": "community.fandom.com",
        "lv": "community.fandom.com",
        "nl": "community.fandom.com",
        "nlhelp": "community.fandom.com",
        "no": "community.fandom.com",
        "pl": "spolecznosc.fandom.com",
        "pt": "comunidade.fandom.com",
        "pt-br": "comunidade.fandom.com",
        "pt-brhelp": "comunidade.fandom.com",
        "pthelp": "comunidade.fandom.com",
        "ro": "community.fandom.com",
        "ru": "community.fandom.com",
        "ruhelp": "community.fandom.com",
        "sr": "community.fandom.com",
        "tr": "community.fandom.com",
        "uk": "spilnota.fandom.com",
        "vi": "community.fandom.com",
        "zh": "community.fandom.com",
    }

    @staticmethod
    def scriptpath(code):
        """The prefix used to locate scripts on this wiki."""
        return {
            "en": "",
            "af": "/nl",
            "ar": "/ar",
            "be": "/ru",
            "bg": "/bg",
            "ca": "",
            "de": "/de",
            "el": "/el",
            "es": "",
            "eshelp": "",
            "et": "/et",
            "fa": "/fa",
            "fi": "",
            "fihelp": "",
            "fr": "/fr",
            "frhelp": "/fr",
            "gl": "",
            "hi": "",
            "hu": "/hu",
            "id": "/id",
            "it": "/it",
            "ithelp": "/it",
            "ja": "/ja",
            "jahelp": "/ja",
            "ko": "/ko",
            "kohelp": "/ko",
            "li": "/li",
            "lv": "/lv",
            "nl": "/nl",
            "nlhelp": "/nl",
            "no": "/no",
            "pl": "",
            "pt": "",
            "pt-br": "",
            "pt-brhelp": "",
            "pthelp": "",
            "ro": "/ro",
            "ru": "/ru",
            "ruhelp": "/ru",
            "sr": "/sr",
            "tr": "/tr",
            "uk": "",
            "vi": "/vi",
            "zh": "/zh",
        }[code]

    @staticmethod
    def protocol(code):
        """The protocol to use to connect to the site."""
        return {
            "en": "https",
            "af": "https",
            "ar": "https",
            "be": "https",
            "bg": "https",
            "ca": "https",
            "de": "https",
            "el": "https",
            "es": "https",
            "eshelp": "https",
            "et": "https",
            "fa": "https",
            "fi": "https",
            "fihelp": "https",
            "fr": "https",
            "frhelp": "https",
            "gl": "https",
            "hi": "https",
            "hu": "https",
            "id": "https",
            "it": "https",
            "ithelp": "https",
            "ja": "https",
            "jahelp": "https",
            "ko": "https",
            "kohelp": "https",
            "li": "https",
            "lv": "https",
            "nl": "https",
            "nlhelp": "https",
            "no": "https",
            "pl": "https",
            "pt": "https",
            "pt-br": "https",
            "pt-brhelp": "https",
            "pthelp": "https",
            "ro": "https",
            "ru": "https",
            "ruhelp": "https",
            "sr": "https",
            "tr": "https",
            "uk": "https",
            "vi": "https",
            "zh": "https",
        }[code]
