name: 修改译名
description: 某事物已有中文译名，提议修改译名。
title: "`艾米莉娅` -> `爱蜜莉雅`"
labels: [ "修改译名" ]
body:
  - type: dropdown
    id: new_src
    attributes:
      label: 新译名来源
      description: "本站的译名优先级为 `官方简体中文译名` > `官方繁体中文译名` > `民间中文译名`，详见 [译名选取规则](https://rezero.fandom.com/zh/wiki/ReZero_Wiki:%E8%AF%91%E5%90%8D%E8%A1%A8#%E9%80%89%E5%8F%96%E8%A7%84%E5%88%99)。"
      multiple: true
      options:
        - 官方简体中文译名
        - 官方繁体中文译名
        - 民间中文译名
    validations:
      required: true
  - type: dropdown
    id: old_src
    attributes:
      label: 旧译名来源
      description: "选填，旧译名的来源。"
      multiple: true
      options:
        - 官方简体中文译名
        - 官方繁体中文译名
        - 民间中文译名
  - type: textarea
    id: extra
    attributes:
      label: 补充说明
      description: 选填，可以补充任何内容。
