name: 新增译名
description: 某事物尚无中文译名，提议新增译名。
title: "`Emilia` -> `艾米莉娅`"
labels: ["新增译名"]
body:
  - type: checkboxes
    id: duplicate-check
    attributes:
      label: 检查重复提议
      description: 前往 [Issues 列表](https://github.com/re0wiki/wiki-bot/issues?q=is%3Aissue) 搜索译名，若已被提出过则直接前往讨论，不必新建 Issue。
      options:
        - label: 该译名未被提出过
          required: true
  - type: textarea
    id: source
    attributes:
      label: 译名的来源
      description: 尽量提供原始来源，而非其他百科等二手来源。
    validations:
      required: true
