from .starts import starts_base, starts_more

jobs: list[list[str]] = [
    ["category", "remove", "-batch", "-from:Image Gallery"],
    ["cosmetic_changes", "-async", "-ignore:method"] + starts_base,
    ["replace", "-automaticsummary", "-fix:HTML"],
    ["replace", "-automaticsummary", "-fix:anti-ve"],
    ["replace", "-automaticsummary", "-fix:date"],
    ["replace", "-automaticsummary", "-fix:gallery"],
    ["replace", "-automaticsummary", "-fix:heading"],
    ["replace", "-automaticsummary", "-fix:isbn"],
    ["replace", "-automaticsummary", "-fix:misc"],
    ["replace", "-automaticsummary", "-fix:para"],
    ["replace", "-automaticsummary", "-fix:specialpages"],
    ["replace", "-automaticsummary", "-fix:syntax"],
    ["replace", "-automaticsummary", "-fix:translation"],
    ["fixing_redirects"] + starts_more,
    ["interwiki", "-quiet", "-async", "-auto", "-force", "-localonly"] + starts_more,
    ["noreferences", "-quiet"] + starts_base,
    ["re0_gallery", "-catr:图库"],
    ["re0_image"],
    ["re0_redirect", "-start:!"],
    ["redirect", "do"],
    ["redirect", "br", "-delete"],
    [
        "template",
        "Character",
        "Infobox character",
        "Re:Zero Light Novel Volumes",
        "Infobox novel",
    ],
    [
        "template",
        "-remove",
        "Parent Tab",
        "Lugnica Navbox",
        "Vollachia Navbox",
        "Gusteko Navbox",
        "Royal Election Navbox",
        "Royal Selection Navbox",
        "Anime Navigation",
        "Manga Navigation",
        "Disambig",
        "LN Navigation",
        "Re:Zero Manga Navigation",
        "Music Navigation",
    ],
    ["touch", "-random:128"],
    ["transferbot", "-lang:en", "-tolang:zh", "-start"],
    [
        "transferbot",
        "-family:w",
        "-lang:zh",
        "-tofamily:re0",
        "-tolang:zh",
        "-start:mediawiki:!",
        "-titleregex:Gadget.*css",
        "-overwrite",
    ],
]
